use_templates:
  - hdci.tmpl.yml
executors:
  sh-c:
    command_++: ["/bin/sh", "-c"]
default_executors: ["with_secret_driver", "sh-c"]
default_script_steps: ["load_secret_driver", "github_checkout"]
triggers:
  - conditions: { gh_event: push }
    stages: [test]
  - conditions: { gh_event: release }
    stages: [test, publish]
stages:
  test:
    jobs:
      run_tests:
        script_ref:
          steps: ["load_secret_driver", "github_checkout", {with_run: {run: "go test -v ./..."}}]
  publish:
    requires: [test]
    jobs:
      build_and_publish:
        script_ref:
          steps: ["load_secret_driver", "github_checkout", {with_run: {run: "go build -o hd-driver-openai ./cmd/hd-driver-openai"}}]
